### ISSUE TITLE
VPN using SSO fails

### ISSUE THREAD

**Issue by krishnaastica** [gate-sso/vpn_gate#4]
Hi,
Thanks for your effort in bringing GATE SSO.
The first think I would like to mention is "It needs a better documentation"

Anyways, I followed the Readme.MD and successfully completed the installation.
But I cannot connect to my OpenVPN-CE using the generated certs and profile.

Is something needs to be done?
Should I configure PLUGIN for authentication in server.conf?

Please suggest / help.
-Thanks,
Krishh

**Comment by krishnaastica** [comment]
And is this applicable to OpenVPN Access server?

**Comment by ajeygore** [comment]
Thanks for this comment, can you please create issue at Gate level?

**Comment by ajeygore** [comment]
Closing old issues, we don't support IPSec anymore.
